# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate, jekyll-sitemap, jekyll-archives]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Aravind Vasudev"
tagline:          "Just another programmer's blog"
description:      "Programming = Life"
baseurl:          /

author:
  name:           'Aravind Vasudevan'
  url:            https://github.com/AravindVasudev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AravindVasudev/AravindVasudev.github.io

paginate_path: "/blog/page:num/"
