# Site settings
title: "Aravind Vasudevan | Yet another programmer's blog"
description: "Student · Full Stack Developer · Machine Learning Enthusiast"
url: 'https://aravindvasudevan.me'
baseurl: '/'
google_analytics: 'UA-83211075-2'
disqus_shortname: 'aravind-vasudev-blog'

author:
  name: 'Aravind Vasudevan'
  email: email@aravindvasudevan.me
  #twitter_username: aravind8896
  #facebook_username: aravind8896
  github_username:  AravindVasudev
  linkedin_username:  aravindvasudev

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jemoji']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
