# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Aravind Vasudev\'s Blog'
tagline:          'Programming = Life'
description:      'Just another programmer\'s blog'
baseurl:          /

author:
  name:           'Aravind Vasudevan'
  url:            https://github.com/AravindVasudev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AravindVasudev/AravindVasudev.github.io
