# Dependencies
markdown:         kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments
gems:             [jekyll-paginate, jekyll-sitemap, jekyll-archives, jemoji]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Aravind Vasudev"
tagline:          "Just another programmer's blog"
description:      "Programming = Life"
baseurl:          /

author:
  name:           'Aravind Vasudevan'
  url:            https://aravindvasudevan.me

url: https://aravindvasudevan.me
enforce_ssl: aravindvasudevan.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AravindVasudev/AravindVasudev.github.io

paginate_path: "/blog/page:num/"
