baseurl: "/"
title: "Blog"
theme: ghostwriter
languageCode: en-us
googleAnalytics: "UA-83211075-2"
pygmentsUseClasses: true
pygmentsCodefences: true
enableEmoji: true

config:
  services:
   disqus:
    shortname: "aravind-vasudev-blog"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

params:
  author:
    name: "Aravind Vasudevan"
    profile: "https://github.com/AravindVasudev"
  mainSections:
    - post
  intro: true
  headline: "Aravind Vasudevan"
  description: "Your friendly neighborhood software engineer."
  github: "https://github.com/AravindVasudev"
  linkedin: "https://linkedin.com/in/aravindvasudev/"
  email: aravind_vasudevan@outlook.com
  opengraph: true
  shareTwitter: false
  rss: true
  shareFacebook: false
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  readingTime: true
  readingTimeText: "Estimated reading time:"

permalinks:
  post: "/:year/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Misc
      url: /misc/
      weight: 2
    - name: About
      url: /about/
      weight: 3